name: 'terraform-apply'

on:
  workflow_dispatch:
    inputs:
      Region:
        description: 'Region'
        default: 'us-central-1'
        required: true
        type: Region

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_PROJECT: sandbox-20220909-4sfsll
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: dev
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/932079530572/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'auto-deploy-standard-svc@sandbox-20220909-4sfsll.iam.gserviceaccount.com'

  Build-Terraform:
    uses: Djackk/gitHub-actions/.github/workflows/worflow-called.yml@main
    with:
      branch: ${{ github.ref }}
      Environment: dev
      Region: ${{ github.event.inputs.Region }}

