name: Call a reusable workflow for stage

on:
  workflow_dispatch:
    inputs:
      Region:
        description: 'Region'
        default: 'us-east-1'
        required: true
        type: String
env:
  Environment: stage

jobs:
  print:
    runs-on: ubuntu-latest
    outputs:
      env_var: ${{ steps.step1.outputs.env_var }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: step1
        run: |
          echo "Environment from caller : $Environment"
          echo "env_var=$Environment" >> $GITHUB_OUTPUT

  call-workflow-passing-data:
    needs:
      - print
    uses: Djackk/gitHub-actions/.github/workflows/worflow-called.yml@main
    with:
      Environment: ${{ needs.print.outputs.env_var}}
      branch: ${{ github.ref }}
      Region: ${{ github.event.inputs.Region }}
