name: Call a reusable workflow for Dev

on:
  workflow_dispatch:
    inputs:
      Region:
        description: 'Region'
        default: 'us-east-1'
        required: true
        type: Region

jobs:
  call-workflow-passing-data:
    uses: Djackk/gitHub-actions/.github/workflows/worflow-called.yml@main
    with:
      Environment: "dev"
      branch: ${{ github.ref }}
      Region: ${{ github.event.inputs.Region }}
